include:
  - board: nice_nano_v2
    shield: mimas_left
  - board: nice_nano_v2
    shield: mimas_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: mimas_dongle prospector_adapter
    cmake-args: -DCONFIG_ZMK_STUDIO=n